// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BlogPreview: typeof import('./components/LandingPage/BlogPreview.vue')['default']
    BlurryCircle: typeof import('./components/LandingPage/BlurryCircle.vue')['default']
    BlurryHeader: typeof import('./components/LandingPage/BlurryHeader.vue')['default']
    ContactParagraph: typeof import('./components/Jobs/ContactParagraph.md')['default']
    Container: typeof import('./components/Container.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    CurlyImageSection: typeof import('./components/LandingPage/CurlyImageSection.vue')['default']
    FAQSection: typeof import('./components/FAQSection.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Hero: typeof import('./components/LandingPage/Hero.vue')['default']
    'HeroiconsOutline:chevronDown': typeof import('~icons/heroicons-outline/chevron-down')['default']
    'HeroiconsOutline:menu': typeof import('~icons/heroicons-outline/menu')['default']
    'HeroiconsSolid:checkCircle': typeof import('~icons/heroicons-solid/check-circle')['default']
    'HeroiconsSolid:x': typeof import('~icons/heroicons-solid/x')['default']
    JobHeader: typeof import('./components/Jobs/JobHeader.md')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    LogoMark: typeof import('./components/LogoMark.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    NewsletterSection: typeof import('./components/LandingPage/NewsletterSection.vue')['default']
    NewsletterSectionOld: typeof import('./components/LandingPage/NewsletterSectionOld.vue')['default']
    OpenPositions: typeof import('./components/Jobs/OpenPositions.vue')['default']
    Popover: typeof import('@headlessui/vue')['Popover']
    PopoverButton: typeof import('@headlessui/vue')['PopoverButton']
    PopoverGroup: typeof import('@headlessui/vue')['PopoverGroup']
    PopoverPanel: typeof import('@headlessui/vue')['PopoverPanel']
    Post: typeof import('./components/Post.vue')['default']
    PostPreview: typeof import('./components/PostPreview.vue')['default']
    PostPreviewItem: typeof import('./components/PostPreviewItem.vue')['default']
    Reliability: typeof import('./components/LandingPage/Reliability.vue')['default']
    SectionHeader: typeof import('./components/SectionHeader.vue')['default']
    StatsSection: typeof import('./components/LandingPage/StatsSection.vue')['default']
    TeamCardItem: typeof import('./components/TeamCardItem.vue')['default']
    Testimonial: typeof import('./components/Testimonial.vue')['default']
    TestimonialSection: typeof import('./components/LandingPage/TestimonialSection.vue')['default']
  }
}

export { }
